# macOS bootstrap for Vic's portable development/agent stack.
# Run with: brew bundle --file ~/dotfiles/Brewfile

tap "homebrew/bundle"
tap "homebrew/services"
tap "hashicorp/tap"
tap "jesseduffield/lazygit"
tap "qmk/qmk"

# Shell / dotfile basics
brew "git"
brew "git-lfs"
brew "gh"
brew "stow"
brew "zsh"
brew "tmux"
brew "fzf"
brew "ripgrep"
brew "fd"
brew "jq"
brew "yq"
brew "bat"
brew "eza"
brew "zoxide"
brew "lazygit"
brew "btop"
brew "duf"
brew "tldr"
brew "wget"
brew "coreutils"
brew "gnu-sed"
brew "gnupg"
brew "pinentry-mac"
brew "mas"

# Language/toolchains
brew "nvm"
brew "pnpm"
brew "bun"
brew "python"
brew "uv"
brew "go"
brew "golangci-lint"
brew "gopls"
brew "rust"
brew "rust-analyzer"
brew "openjdk@17"
brew "node" # fallback/system node; pi stack should normally use nvm-managed Node 24+

# Dev infrastructure
brew "awscli"
brew "docker-compose"
brew "kubernetes-cli"
brew "kubectx"
brew "helm"
brew "hashicorp/tap/terraform"
brew "postgresql@16"
brew "libpq"
brew "protobuf"
brew "graphviz"
brew "libimobiledevice"
brew "pillow"
brew "rover"
brew "sbt"
brew "nmap"
brew "hurl"
brew "tailscale"

# Editors / terminals / local apps
cask "1password"
brew "1password-cli"
cask "amethyst"
cask "basictex"
cask "ghostty"
cask "cursor"
cask "visual-studio-code"
cask "docker"
cask "google-chrome"
cask "firefox"
cask "obsidian"
cask "slack"
cask "zoom"
cask "postman"
cask "android-studio"

# Fonts
cask "font-meslo-lg-nerd-font"
cask "font-fira-code"
cask "font-fira-code-nerd-font"

# Optional keyboard / embedded tooling kept from the old Mac setup
brew "qmk/qmk/qmk"
