[env]
TERM = "xterm-256color"

[font]
size = 7

[font.bold]
family = "FiraCode Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "FiraCode Nerd Font Mono"
style = "Bold"

[font.italic]
family = "FiraCode Nerd Font Mono"
style = "Light"

[font.normal]
family = "FiraCode Nerd Font Mono"
style = "Medium"
